### ISSUE TITLE
Bibdesk cache not found 

### ISSUE THREAD

**Issue by rtwld** [fractaledmind/alfred_bibquery#1]
BibQuery v101
Alfred 2.3 (264)
BibDesk 1.6.2 (3071)

```
Starting debug for 'BibQuery'
[ERROR: alfred.workflow.input.scriptfilter] Code 1: 02:11:46 workflow.py:1199 ERROR    [Errno 2] No such file or directory: '/Users/dan/Library/Caches/Metadata/edu.ucsd.cs.mmccrack.bibdesk/'
Traceback (most recent call last):
  File "/Users/dan/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.FC8708C5-BBDF-49BD-B48F-25A75F18C1DA/workflow/workflow.py", line 1197, in run
    func(self)
  File "bibquery.py", line 442, in main
    filter(queries, scope, wf)
  File "bibquery.py", line 420, in filter
    simple_filter(query, scope, wf)
  File "bibquery.py", line 310, in simple_filter
    data = read_cachedir()
  File "bibquery.py", line 80, in read_cachedir
    for bib in os.listdir(BIB_DIR):
```

I checked and on my system `edu.ucsd.cs.mmccrack.bibdesk` is located in the parent `Caches` folder, not in `Caches/Metadata`. Deleting the directory doesn't fix the problem, it gets created again in the same place.

**Comment by rtwld** [comment]
Simply changing the path (see rtwld/alfred_bibquery@b2f657db00f5b42735fa64645313c6bb0d120389) doesn't work either:

```
BplistError: Bad file header
[ERROR: alfred.workflow.input.scriptfilter] Code 1: 02:58:14 workflow.py:1199 ERROR    Bad file header
Traceback (most recent call last):
  File "/Users/dan/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.6F5EBB81-5BD2-4893-BA43-0313BC3BC2EB/workflow/workflow.py", line 1197, in run
    func(self)
  File "bibquery.py", line 444, in main
    filter(queries, scope, wf)
  File "bibquery.py", line 422, in filter
    simple_filter(query, scope, wf)
  File "bibquery.py", line 312, in simple_filter
    data = read_cachedir()
  File "bibquery.py", line 85, in read_cachedir
    bib_data = ccl_bplist.load(_file)
  File "/Users/dan/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.6F5EBB81-5BD2-4893-BA43-0313BC3BC2EB/ccl_bplist.py", line 258, in load
    raise BplistError("Bad file header")
```

It seems the plist isn't there. Any ideas?

**Comment by rtwld** [comment]
Turns out just changing any setting in the BibDesk Preferences creates `Caches/Metadata/edu.ucsd.cs.mmccrack.bibdesk`. It works fine now.

So, this is a problem/bug on BibDesk's part, but you might want to check for the existence of the folder before parsing the byte plist.

**Comment by fractaledmind** [comment]
Well, I must say, this is exactly how I love an issue to evolve. :) I appreciate you attempting to work this out on your own. 

You are right tho, I do need to add a check for the dir's existence. To be honest, this workflow isn't really as maintained as my others. I use Zotero over BibDesk. I made this as a "service to the community" more than anything else. So, if you plan on using this actively, I can promise to review pull requests and keep up with you. Otherwise, I don't see this evolving much beyond this basic setup. I just don't have the time...

**Comment by rtwld** [comment]
I use Zotero to manage my bibliography and I would love to use ZotQuery (_great job_ you did there btw)! 

The reason keeping me from using it is that I want to delegate the bibliography creation to pandoc (viz. the biblatex backend) because of the many [CSL styles](http://citationstyles.org) that are available. I haven't looked at the code, but it seem that ZQ doesn't take advantage of the CSL repository. (I deduce this from the fact that, as of now, ZQ only offers limited formats.) You sort of reinvent the wheel this way, don't you? 

Also, I love to have a unique *markdown (well, scrivener) file which I can export with pandoc to all kind of formats (pdf, tex, docx) and choose the CSL at conversion time. For all I know ZQ "hardcodes" a certain inline citation and bibliography style while writing, isn't that correct?

I read somewhere that you don't like citekeys (well, the function of citekeys). I guess that having already the formatted inline citations and bibliography circumvents that. But I don't see the problem with citekeys. Indeed, I followed your [indication](http://www.alfredforum.com/topic/4346-bibquery-search-bibdesk-from-alfred/?p=27273) and [added them](https://github.com/rtwld/alfred_bibquery/commit/b2f657db00f5b42735fa64645313c6bb0d120389) to BibQuery, so I see only the drawbacks of generating formatted citations and bibliography while writing.

Still, I could use ZotQuery just to paste the citekeys in my markdown (well, scrivener) document, but I need the .bib document anyway for pandoc, so I automatically export it from Zotero and feed it to BQ. 

Do you have any performance comparisons ZQ vs. BQ regarding wrt to loading large bibliographies?

**Comment by rtwld** [comment]
Oh, I just noticed that my comment above doesn't really belong in this thread. But it's also not really a technical issue with ZQ, more a conceptual one, so I don't really know where to have this conversation online. Sorry about that.

**Comment by fractaledmind** [comment]
Let me move thru your comments in order. The current functionality of ZotQuery is the way it is partially due to personal preference but also partially to ensure "safe simplicity". By that I mean, I didn't want to add "too much" (I know, I probably didn't follow my own advice well enough) because that only increases my responsibility to users. The more I rely on 3rd party things, the more difficult it is to keep ZotQuery working well for everyone. The reason I avoided direct citekey functionality is because Zotero doesn't support it. A program like BIbDesk holds/stores its data in a `.bib` file. That's its data structure. Zotero stores everything in a `.sqlite` database. Of course, you can export your library into a `.bib`, but that requires manual work to keep the `.bib` up-to-date. Plus, I use the Zotero online API to generate bibtex citekeys. By default, however, Zotero's online API and the manual Zotero `.bib` export do not use the same citekey format. All this is to say, I didn't want to open this can of worms. 

Now, that isn't to say that this won't work for someone interested in doing the backend work themselves. As you can see, ZotQuery can export BibTeX. So, you can roll into into pandoc easily. Either [1] you use ZotQuery to generate the both the intext citekeys as well as the `.bib` file or [2] you can use the Better BibTeX add-on for Zotero to ensure that your manually exported `.bib` file has the same citekey format. 

Note, however, that I am working on a ZotQuery preprocessor that will allow users to have access to the full CSL repository of styles, but doesn't depend on BibTeX. Side note, it is BibTeX I don't like, not citekeys themselves. 

I'm hopping on a plane, so I have to stop here. But hopefully this is enough to set you on the right track.

**Comment by rtwld** [comment]
Thanks a bunch for your input! Selecting the right amount of features is always difficult and I understand now why you couldn't implement citekeys by relying on Zotero's data structure. That said, it is also a matter of taste set by the developer. It's about the right tool for his/her personal use case, and rightly so. 

I'll try to experiment with ZotQuery and an inbetween BibLaTeX backend. Thanks for pointing me to the Better BibTeX add-on, I didn't know about that. I took a glance at it and it seems to be a goldmine!!

Good to hear that you're gonna integrate the full CSL repository. That's a killer feature!
